Fail recoverFromCancelReusesConnection() on unexpected response

This may help nail down the sporadic timeouts in this test.
