[+++ b/rxjava-core/src/test/java/rx/observers/SafeObserverTest.java, +import java.util.List;, +            List<Throwable> innerExceptions = ((CompositeException) e2).getExceptions();, +            assertEquals(2, innerExceptions.size());, +            Throwable e3 = innerExceptions.get(0);, +            assertTrue(e3 instanceof SafeObserverTestException);, +            assertEquals("error!", e3.getMessage());, +            Throwable e4 = innerExceptions.get(1);, +            assertTrue(e4 instanceof SafeObserverTestException);, +            assertEquals("onErrorFail", e4.getMessage());, +            List<Throwable> innerExceptions = ((CompositeException) e2).getExceptions();, +            assertEquals(2, innerExceptions.size());, +            Throwable e3 = innerExceptions.get(0);, +            assertTrue(e3 instanceof SafeObserverTestException);, +            assertEquals("onNextFail", e3.getMessage());, +            Throwable e4 = innerExceptions.get(1);, +            assertTrue(e4 instanceof SafeObserverTestException);, +            assertEquals("onErrorFail", e4.getMessage());, +            List<Throwable> innerExceptions = ((CompositeException) e2).getExceptions();, +            assertEquals(3, innerExceptions.size());, +            Throwable e3 = innerExceptions.get(0);, +            assertTrue(e3 instanceof SafeObserverTestException);, +            assertEquals("onError failure", e3.getMessage());, +            Throwable e4 = innerExceptions.get(1);, +            assertTrue(e4 instanceof SafeObserverTestException);, +            assertEquals("onErrorFail", e4.getMessage());, +            Throwable e5 = innerExceptions.get(2);, +            assertTrue(e5 instanceof SafeObserverTestException);, +            assertEquals("failure from unsubscribe", e5.getMessage());, +            List<Throwable> innerExceptions = ((CompositeException) e2).getExceptions();, +            assertEquals(2, innerExceptions.size());, +            Throwable e3 = innerExceptions.get(0);, +            assertTrue(e3 instanceof SafeObserverTestException);, +            assertEquals("error!", e3.getMessage());, +            Throwable e4 = innerExceptions.get(1);, +            assertTrue(e4 instanceof SafeObserverTestException);, +            assertEquals("failure from unsubscribe", e4.getMessage());]