[+++ b/guava/src/com/google/common/util/concurrent/AbstractFuture.java, +          throw cancellationExceptionWithCause(, +              "Task was cancelled.", exception);, +        // Don't actually construct a CancellationException until necessary., +        this.exception = isCancelled(), +            ? new CancellationException("Future.cancel() was called.") : t;, +, +  static final CancellationException cancellationExceptionWithCause(, +      String message, Throwable cause) {, +    CancellationException exception = new CancellationException(message);, +    exception.initCause(cause);, +    return exception;, +  }]