Isolate thrown exception in AssertTests
